.\" Manpage for massh-enum.
.\" Contact trimstray@gmail.com.
.TH man 8 "17.08.2018" "1.0.0" "massh-enum man page"
.SH NAME
massh-enum \-
.SH SYNOPSIS
massh-enum <option|long-option>
.SH DESCRIPTION
.SH OPTIONS
--help
        show this message
.SH SEE ALSO
https://github.com/trimstray/massh-enum
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
